version: "3.8"

services:
  cache:
    build:
      context: .
      dockerfile: Dockerfile.cache
    environment:
      - CACHE_PORT=${DRAGONFLY_PORT:-6379}
    healthcheck:
      test: ["CMD", "dragonfly-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "${DRAGONFLY_PORT:-6379}:${DRAGONFLY_PORT:-6379}"
